name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npx eslint "src/**/*.{js,ts,tsx}" --max-warnings=0

      - name: Build
        run: npm run build

      - name: Lighthouse CI
        uses: lighthouse-ci/action@v2
        with:
          configPath: .lighthouseci/config.js
          uploadTarget: temporary-public-storage
